### ISSUE TITLE
load_state_dict_from_url is not defined

### ISSUE THREAD

**Issue by ghost** [stigma0617/VoVNet.pytorch#1]
Because vovnet.py does not import load_state_dict_from_url,
"the state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)" is not valid in Line 185-186.
I guess vovnet.py should import a module such as utils.

**Comment by sbl1996** [comment]
The model_urls are dropbox urls and load_state_dict_from_url cannot download model files by these urls directly. I suggest the author to put these files directly in the repo. It would be better to follow torch.hub's protocol to publish models. See https://pytorch.org/docs/stable/hub.html for detail.

**Comment by stigma0617** [comment]
@NobuhikoWakai  We modified it. Try it again.
