### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by 2anchao** [stigma0617/VoVNet.pytorch#3]
I use the vovnet39 without pretrained weights , the result show vovnet is fast and powerful.so I want pretrained model for transfer learning, but the Link that you provide is not useful,can you upload the pretrained model.thanks.

**Comment by stigma0617** [comment]
@2anchao Hi,

When I click this [path](https://dl.dropbox.com/s/1lnzsgnixd8gjra/vovnet39_torchvision.pth?dl=1), the pretrained weight can be downloaded well.

Could you explain more details about reproducing your problem?

**Comment by 2anchao** [comment]
> @2anchao Hi,
> When I click this path, the pretrained weight can be downloaded well.
> Could you explain more details about reproducing your problem?
When I click the link，display not accessible to website,can you send me an email with pretrained weights(an_chao1994@163.com)

**Comment by 2anchao** [comment]
@stigma0617 
When I click the link，display not accessible to website,can you send me an email with pretrained weights(an_chao1994@163.com)

**Comment by stigma0617** [comment]
You can get the weight file by this command.

> wget https://dl.dropbox.com/s/1lnzsgnixd8gjra/vovnet39_torchvision.pth?dl=1

**Comment by 2anchao** [comment]
@stigma0617 
I have tried this method, but failed,the terminal display "Connection timed out".so....what should I do?  QAQ

**Comment by stigma0617** [comment]
@2anchao,

then why don't you just click this https://dl.dropbox.com/s/1lnzsgnixd8gjra/vovnet39_torchvision.pth?dl=1?
