### ISSUE TITLE
confused about the code

### ISSUE THREAD

**Issue by xiaomingwang80** [stigma0617/VoVNet.pytorch#4]
https://github.com/stigma0617/VoVNet.pytorch/blob/039d9dcbd07de73fb5b8cc14bdde483a3807225c/models_vovnet/vovnet.py#L106
Hello, I am a little confused with this line, it seems that 'module_name'  should be a String, but the value f'OSA{stage_num}_1' make me feel puzzled. Could you give me some explanation?
Looking for your reply. Thank you.

**Comment by stigma0617** [comment]
@wangxiaoming1886 Hi,

You mean  f-string format?

You can find the information about [python3.7 f-string](https://www.python.org/dev/peps/pep-0498/) .

**Comment by xiaomingwang80** [comment]
Thank you for your reply!
And I also have another question. 
In the paper,  the overall architecture of VoVNet (table 1.) shows that Stem Stage 1 contains 3 conv, the stride of which are 2/1/1 respectively. However, your code (https://github.com/stigma0617/VoVNet.pytorch/blob/039d9dcbd07de73fb5b8cc14bdde483a3807225c/models_vovnet/vovnet.py#L136
)shows that the stride are 2/1/2, is that a mistake?

**Comment by stigma0617** [comment]
@wangxiaoming1886 

In order to reduce memory consumption, 

we remove 3x3 maxpooling  and change the stride of third 3x3 conv from 1 to 2.

**Comment by xiaomingwang80** [comment]
@stigma0617 
Got it! Thank you so much!
